--@Autor(es):       Alejandro Barreiro Valdez y Jessica Zepeda Baeza
--@Fecha creación:  03/06/2022
--@Descripción:     Creación de objetos

connect bz_proy_admin/proyecto

--
-- tabla: puesto
--
create table puesto(
  puesto_id             number(10,0)    not null 
  constraint puesto_pk primary key,
  clave                 varchar2(3)     not null,
  nombre                varchar2(50)    not null,
  descripcion           varchar2(500)   not null,
  fecha_inicio_vigencia date            not null,
  fecha_fin_vigencia    date,
  sueldo_mensual        number(8,2)     not null
);

--
-- tabla: empleado
--
create table empleado(
  empleado_id       number(10,0)    not null 
  constraint empleado_pk primary key,
  nombre            varchar2(15)    not null,
  ap_paterno        varchar2(15)    not null,
  ap_materno        varchar2(15)    not null,
  curp              varchar2(18)    not null
  constraint empleado_curp_uk unique,
  rfc               varchar2(13)    not null
  constraint empleado_rfc_uk unique,
  fecha_nacimiento  date            not null,
  actividad         number(1,0)     default 1 not null,
  tipo              varchar2(1)     not null,
  fecha_puesto      date            default sysdate not null,
  puesto_id         number(10,0)    not null
  constraint puesto_id_fk references puesto(puesto_id),
  constraint empleado_tipo_chk check(tipo in('S', 'H', 'B')),
  constraint empleado_actividad_chk check(actividad in (0,1))
);

--
-- tabla: nivel empleado
--
create table nivel_empleado(
  nivel_empleado_id         number(10,0)   not null
  constraint nivel_empleado_pk primary key,
  clave                     varchar2(15),
  descripcion               varchar2(350)
);

--
-- tabla: empleado de base
--
create table empleado_de_base(
  empleado_id       number(10,0)   not null
  constraint empleado_base_pk primary key,
  num_empleado_base     number(10,0) generated by default on null 
  as identity 
  start with 1
  increment by 1
  nominvalue
  nomaxvalue
  cache 20
  noorder,
  fecha_inicio          date            not null,
  protesta              blob            not null,
  nivel_empleado_id     number(10,0)   not null
  constraint eb_nivel_empleado_id_fk references nivel_empleado(nivel_empleado_id),
  constraint eb_empleado_id_fk foreign key(empleado_id) 
  references empleado(empleado_id)
);

--
-- tabla: proyecto
--
create table proyecto(
  proyecto_id               number(10,0)   not null
  constraint proyecto_pk primary key,
  nombre                    varchar2(40)    not null,
  descripcion               varchar2(500)   not null,
  num_partida_presupuestal  varchar2(8)     not null
);

--
-- tabla: empleado por honorarios
--
create table empleado_por_honorarios(
  empleado_id           number(10,0)   not null
  constraint empleado_honorario_pk primary key,
  proyecto_id           number(10,0)   not null
  constraint eh_proyecto_id_fk references proyecto(proyecto_id),
  empleado_contrato_id  number(10,0)   not null
  constraint eh_empleado_contrato_id_fk references empleado_de_base(empleado_id),
  constraint eh_empleado_id_fk foreign key(empleado_id) 
  references empleado(empleado_id)
);

--
-- tabla: becario
--
create table becario(
  empleado_id       number(10,0)   not null
  constraint becario_pk primary key,
  universidad       varchar2(50)    not null,
  carrera           varchar2(40)    not null,
  fecha_titulacion  date            not null,
  promedio          number(5,2)    not null,
  constraint becario_empleado_id_fk foreign key(empleado_id) 
  references empleado(empleado_id),
  constraint becario_promedio_chk check(promedio <= 100.00)
);

--
-- tabla: empleado_email
--
create table empleado_email(
  empleado_email_id     number(10,0)   not null
  constraint empleado_email_pk primary key,
  email                 varchar2(50)    not null,
  empleado_id           number(10,0)   not null
  constraint email_empleado_id_fk references empleado(empleado_id)
);

--
-- tabla: historico_puesto
--
create table historico_puesto(
  historico_puesto_id   number(10,0)   not null 
  constraint historico_puesto_pk primary key,
  fecha_puesto          date            not null,
  puesto_id             number(10,0)   not null
  constraint hp_puesto_id_fk references puesto(puesto_id),
  empleado_id           number(10,0)   not null
  constraint hp_empleado_id_fk references empleado(empleado_id)
);

--
-- tabla: quincena
--
create table quincena(
  quincena_id       number(10,0)   not null
  constraint quincena_pk primary key,
  anio              number(4,0)    not null,
  num_quincena      number(2,0)    not null
);

--
-- tabla: concepto_pago
--
create table concepto_pago(
  concepto_pago_id          number(10,0)   not null
  constraint concepto_pago_pk primary key,
  clave                     varchar2(4)     not null,
  nombre                    varchar2(20)    not null,
  descripcion               varchar2(150)   not null,
  tipo                      varchar2(1)     not null,
  constraint concepto_pago_tipo_chk check(tipo in('P','D'))
);

--
-- tabla: contrato
--
create table contrato(
  contrato_id               number(10,0)   not null
  constraint contrato_pk primary key,
  num_contrato              number(10,0)   not null,
  fecha_inicio              date           not null,
  fecha_fin                 date           not null,
  pdf                       blob           not null,
  empleado_id               number(10,0)   not null
  constraint c_empleado_id_fk references empleado(empleado_id)
);

--
-- tabla: registro
--
create table registro(
  empleado_id       number(10,0)   not null
  constraint registro_pk primary key,
  foto              blob            not null,
  huella_p_izq      blob            not null,
  huella_p_der      blob            not null,
  huella_i_izq      blob            not null,
  huella_i_der      blob            not null,
  huella_m_izq      blob            not null,
  huella_m_der      blob            not null,
  huella_a_izq      blob            not null,
  huella_a_der      blob            not null,
  huella_men_izq    blob            not null,
  huella_men_der    blob            not null
);

--
-- tabla: credencial
--
create table credencial(
  credencial_id         number(10,0)   not null
  constraint credencial_pk primary key,
  folio                 varchar2(5)    not null,
  num_emision           number(10,0)   not null,
  fecha_emision         date           not null,
  vigencia              number(1,0)    default 1 not null,
  empleado_id           number(10,0)   not null
  constraint cre_empleado_id_fk references empleado(empleado_id),
  credencial_ant_id     number(10,0)
  constraint c_credencial_ant_id_fk references credencial(credencial_id),
  constraint credencial_vigencia_chk check(vigencia in (0,1))
);

--
-- tabla: nomina
--
create table nomina(
  nomina_id             number(10,0)   not null
  constraint nomina_pk primary key,
  fecha_generacion      date            not null,
  fecha_pago            date            not null,
  importe_total         number(11,2)   not null,
  pagos_generados       number(10,0)   not null,
  pagos_no_cobrados     number(10,0)   not null,
  porcentaje_no_pagados 
  generated always as ((pagos_no_cobrados/pagos_generados)*100) virtual,
  quincena_id           number(10,0)   not null
  constraint nomina_quincena_id_fk references quincena(quincena_id),
  constraint nomina_quincena_id_uk unique (quincena_id)
);


--
-- tabla: empleado_nomina
--
create table empleado_nomina(
  empleado_nomina_id    number(10,0)   not null
  constraint empleado_nomina_pk primary key,
  importe               number(9,2)    not null,     
  empleado_id           number(10,0)   not null
  constraint en_empleado_id_fk references empleado(empleado_id),
  nomina_id             number(10,0)   not null
  constraint en_nomina_id_fk references nomina(nomina_id)
);

--
-- tabla: empleado_nomina_concepto
--
create table empleado_nomina_concepto(
  empleado_nomina_concepto_id   number(10,0)   not null
  constraint empleado_nomina_concepto_pk primary key,
  importe                       number(9,2)    not null,     
  empleado_nomina_id            number(10,0)   not null
  constraint enc_empleado_nomina_id_fk 
  references empleado_nomina(empleado_nomina_id),
  concepto_pago_id              number(10,0)   not null
  constraint en_concepto_pago_id_fk references concepto_pago(concepto_pago_id)
);

--
-- tabla: beneficiario
--
create table beneficiario(
  beneficiario_id     number(10,0)   not null
  constraint beneficiario_pk primary key,
  nombre              varchar2(15)    not null,
  ap_paterno          varchar2(15)    not null,
  ap_materno          varchar2(15)    not null,
  porcentaje          number(5,2)    not null,
  parentesco          varchar2(15)    not null,
  empleado_id         number(10,0)   not null
  constraint b_empleado_id_fk references empleado(empleado_id),
  constraint b_porcentaje_chk check (porcentaje <= 100.0)
);

--
-- tabla: incidencia
--
create table incidencia(
  empleado_id       number(10,0)   not null
  constraint i_empleado_id_fk references empleado(empleado_id),
  folio             number(10,0)   not null,
  fecha_registro    date            not null,
  descripcion       varchar2(200)   not null,
  constraint incidencia_pk primary key(empleado_id, folio)
);
